//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTypeInterrogator.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileTypeInterrogator.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;123&quot;: {
        ///    &quot;signs&quot;: [
        ///      &quot;0,00001A00051004&quot;
        ///    ],
        ///    &quot;mime&quot;: &quot;application/vnd.lotus-1-2-3&quot;,
        ///    &quot;name&quot;: &quot;Lotus 1-2-3 Spreadsheet&quot;
        ///  },
        ///  &quot;3g2&quot;: {
        ///    &quot;signs&quot;: [
        ///      &quot;0,0000001466747970336770&quot;,
        ///      &quot;0,0000002066747970336770&quot;
        ///    ],
        ///    &quot;mime&quot;: &quot;video/3gpp2&quot;,
        ///    &quot;name&quot;: &quot;3GPP2 Multimedia File&quot;
        ///  },
        ///  &quot;3gp&quot;: {
        ///    &quot;signs&quot;: [
        ///      &quot;0,0000001466747970336770&quot;,
        ///      &quot;0,0000002066747970336770&quot;
        ///    ],
        ///    &quot;mime&quot;: &quot;video/3gpp&quot;,
        ///    &quot;name&quot;: &quot;3GPP Multimedia File&quot;
        ///  },
        ///  &quot;7z&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string definitions {
            get {
                return ResourceManager.GetString("definitions", resourceCulture);
            }
        }
    }
}
